### PR TITLE
Update calc.php

### PR DESCRIPTION
**Pull request by ryusoft**
Seem like this is the correct logic ? total qty of cart, instead line item.

### CODE REVIEW

**Comment by ryusoft** [comment]
Initially just expected to buy one product at a time, hehe~ that why called simple shopping app, kind of express checkout, sorely one item, but then since your discount apply to all items, if buy one item qty 2, the other qty 1, the discount you apply to total value, so the qty should follow as well.

**Comment by r0lodex** [comment]
Yeah. That makes sense. Anyway, it's your rule. Thanks for the PR though

**Comment by r0lodex** [comment]
But you making the PR is like cheating on the test, no? Hehe

**Comment by ryusoft** [comment]
lol~ just **play around**, and _suggest changes_, as I am not so active on github.

**Pull request merged**
